### ISSUE TITLE
[Error]has no exported member 'AsyncAction'

### ISSUE THREAD

**Issue by zeatan** [crescware/walts#11]
Hello,

Following error occurrs.

`ERROR in node_modules/walts/index.d.ts (1,39): Module '"node_modules/walts/src/actions"' has no exported member 'AsyncAction'.`

commit dc59408f331f4fd6d9ccee47c769e30da860468e maybe related...

**Comment by okunokentaro** [comment]
Hi.

Thank you for your report and sorry for my late reply.
It has fixed in `0.11.1`. Please try it.
